"""
Plan Creation System for Personal AI Employee
Enables AI to create, manage, and execute project plans following SDD methodology
"""
import os
import json
import time
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional
import importlib.util


class PlanCreationSystem:
    def __init__(self, vault_path: str = "AI_Employee_Vault"):
        self.vault_path = Path(vault_path)
        self.specs_path = self.vault_path / "specs"
        self.tasks_path = self.vault_path / "tasks"
        self.plans_path = self.vault_path / "plans"

        # Create necessary directories
        self.specs_path.mkdir(parents=True, exist_ok=True)
        self.tasks_path.mkdir(parents=True, exist_ok=True)
        self.plans_path.mkdir(parents=True, exist_ok=True)

    def create_spec(self, feature_name: str, description: str, requirements: List[str],
                   acceptance_criteria: List[str], constraints: List[str] = None) -> str:
        """Create a feature specification following SDD methodology"""

        spec_content = f"""# {feature_name.replace('_', ' ').title()} Specification

## Feature Description
{description}

## Requirements
{chr(10).join([f'- {req}' for req in requirements])}

## Acceptance Criteria
{chr(10).join([f'- {ac}' for ac in acceptance_criteria])}

## Constraints
{chr(10).join([f'- {c}' for c in (constraints or [])])}

## Success Metrics
- Implementation follows SDD methodology (spec -> plan -> tasks -> implementation)
- All acceptance criteria are met
- Code follows project standards and conventions

## Timeline
- Spec creation: {datetime.now().isoformat()}
- Planned completion: [To be determined in plan phase]

## Dependencies
- None at this time

## Out of Scope
- Implementation details (covered in plan phase)
- Specific technical approaches (covered in plan phase)
- Non-functional requirements (covered in plan phase)

---

**Generated by Plan Creation System on {datetime.now().isoformat()}**
"""

        spec_file = self.specs_path / f"{feature_name.lower()}_spec.md"
        with open(spec_file, 'w', encoding='utf-8') as f:
            f.write(spec_content)

        print(f"Created spec: {spec_file.name}")
        return str(spec_file)

    def create_plan(self, feature_name: str, architecture: str, technology_stack: List[str],
                   implementation_approach: str, risk_assessment: List[str],
                   non_functional_requirements: List[str]) -> str:
        """Create a detailed implementation plan"""

        plan_content = f"""# {feature_name.replace('_', ' ').title()} Implementation Plan

## Architecture Overview
{architecture}

## Technology Stack
{chr(10).join([f'- {tech}' for tech in technology_stack])}

## Implementation Approach
{implementation_approach}

## Risk Assessment
{chr(10).join([f'- {risk}' for risk in risk_assessment])}

## Non-Functional Requirements
{chr(10).join([f'- {nfr}' for nfr in non_functional_requirements])}

## Implementation Phases
### Phase 1: Setup and Configuration
- [ ] Set up development environment
- [ ] Configure necessary services
- [ ] Establish basic project structure

### Phase 2: Core Implementation
- [ ] Implement core functionality
- [ ] Add error handling and validation
- [ ] Implement logging and monitoring

### Phase 3: Testing and Validation
- [ ] Write unit tests
- [ ] Perform integration testing
- [ ] Validate against acceptance criteria

### Phase 4: Deployment and Documentation
- [ ] Prepare deployment artifacts
- [ ] Create user documentation
- [ ] Perform final validation

## Resources Required
- Development time: [To be estimated]
- Infrastructure: [To be specified]
- Third-party services: [To be specified]

## Success Criteria
- Implementation follows the defined architecture
- All acceptance criteria from spec are met
- Code quality meets project standards
- Performance requirements are satisfied

---

**Generated by Plan Creation System on {datetime.now().isoformat()}**
"""

        plan_file = self.plans_path / f"{feature_name.lower()}_plan.md"
        with open(plan_file, 'w', encoding='utf-8') as f:
            f.write(plan_content)

        print(f"Created plan: {plan_file.name}")
        return str(plan_file)

    def create_tasks(self, feature_name: str, task_list: List[Dict[str, Any]]) -> str:
        """Create a detailed task list for implementation"""

        tasks_content = f"""# {feature_name.replace('_', ' ').title()} Implementation Tasks

## Task List

"""

        for i, task in enumerate(task_list, 1):
            tasks_content += f"### Task {i}: {task['title']}\n\n"
            tasks_content += f"**Description:** {task['description']}\n\n"
            tasks_content += f"**Implementation Approach:** {task['approach']}\n\n"
            tasks_content += f"**Acceptance Criteria:**\n"
            for ac in task['acceptance_criteria']:
                tasks_content += f"- [ ] {ac}\n"
            tasks_content += "\n"

            if 'dependencies' in task and task['dependencies']:
                tasks_content += f"**Dependencies:** {', '.join(task['dependencies'])}\n\n"

        tasks_content += f"""## Task Execution Guidelines
- Execute tasks in sequence unless dependencies allow parallel execution
- Update task status as completed after implementation
- Document any deviations from the plan in the implementation notes
- Run tests after each completed task when applicable

---

**Generated by Plan Creation System on {datetime.now().isoformat()}**
"""

        tasks_file = self.tasks_path / f"{feature_name.lower()}_tasks.md"
        with open(tasks_file, 'w', encoding='utf-8') as f:
            f.write(tasks_content)

        print(f"Created tasks: {tasks_file.name}")
        return str(tasks_file)

    def execute_task(self, task_description: str, code_changes: Dict[str, str] = None) -> bool:
        """Execute a specific task and potentially make code changes"""

        print(f"Executing task: {task_description}")

        if code_changes:
            for file_path, content in code_changes.items():
                file_path_obj = Path(file_path)
                file_path_obj.parent.mkdir(parents=True, exist_ok=True)

                with open(file_path_obj, 'w', encoding='utf-8') as f:
                    f.write(content)

                print(f"Created/updated file: {file_path_obj}")

        print(f"Completed task: {task_description}")
        return True

    def generate_plan_from_spec(self, spec_content: str) -> Dict[str, Any]:
        """Generate a plan based on a specification"""
        # This would typically involve parsing the spec and generating a plan
        # For now, we'll return a basic plan structure
        return {
            "architecture": "Modular architecture following project patterns",
            "technology_stack": ["Python", "FastAPI", "SQLAlchemy", "Pydantic"],
            "implementation_approach": "Follow SDD methodology with spec -> plan -> tasks -> implementation phases",
            "risk_assessment": [
                "Dependencies may not be available as expected",
                "Integration with external services may fail",
                "Performance requirements may not be met"
            ],
            "non_functional_requirements": [
                "Response time < 100ms for 95% of requests",
                "System availability > 99.9%",
                "Secure handling of sensitive data"
            ]
        }

    def generate_tasks_from_plan(self, plan_content: str) -> List[Dict[str, Any]]:
        """Generate tasks based on a plan"""
        # This would typically involve parsing the plan and generating tasks
        # For now, we'll return a basic task structure
        return [
            {
                "title": "Set up project structure",
                "description": "Create necessary directories and files for the feature",
                "approach": "Follow project conventions and patterns",
                "acceptance_criteria": [
                    "Directory structure follows project patterns",
                    "Files are properly organized",
                    "Basic imports and dependencies are set up"
                ],
                "dependencies": []
            },
            {
                "title": "Implement core functionality",
                "description": "Create the main functionality of the feature",
                "approach": "Implement according to architecture and design",
                "acceptance_criteria": [
                    "Core functionality works as specified",
                    "Error handling is implemented",
                    "Input validation is in place"
                ],
                "dependencies": ["Set up project structure"]
            },
            {
                "title": "Add testing and documentation",
                "description": "Write tests and documentation for the feature",
                "approach": "Follow testing and documentation standards",
                "acceptance_criteria": [
                    "Unit tests cover critical paths",
                    "Integration tests verify functionality",
                    "Documentation is clear and accurate"
                ],
                "dependencies": ["Implement core functionality"]
            }
        ]

    def run_plan_creation_workflow(self, feature_name: str, description: str,
                                 requirements: List[str], acceptance_criteria: List[str]):
        """Run the complete plan creation workflow: spec -> plan -> tasks"""

        print(f"Starting plan creation workflow for: {feature_name}")

        # Step 1: Create spec
        print("1. Creating specification...")
        spec_path = self.create_spec(
            feature_name=feature_name,
            description=description,
            requirements=requirements,
            acceptance_criteria=acceptance_criteria
        )

        # Step 2: Generate and create plan
        print("2. Generating and creating plan...")
        spec_content = Path(spec_path).read_text()
        plan_data = self.generate_plan_from_spec(spec_content)

        plan_path = self.create_plan(
            feature_name=feature_name,
            architecture=plan_data["architecture"],
            technology_stack=plan_data["technology_stack"],
            implementation_approach=plan_data["implementation_approach"],
            risk_assessment=plan_data["risk_assessment"],
            non_functional_requirements=plan_data["non_functional_requirements"]
        )

        # Step 3: Generate and create tasks
        print("3. Generating and creating tasks...")
        plan_content = Path(plan_path).read_text()
        task_list = self.generate_tasks_from_plan(plan_content)

        tasks_path = self.create_tasks(feature_name=feature_name, task_list=task_list)

        print(f"Plan creation workflow completed!")
        print(f"- Spec: {spec_path}")
        print(f"- Plan: {plan_path}")
        print(f"- Tasks: {tasks_path}")

        return {
            "spec": spec_path,
            "plan": plan_path,
            "tasks": tasks_path
        }


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Plan Creation System for Personal AI Employee")
    parser.add_argument("--vault-path", default="AI_Employee_Vault", help="Path to AI Employee vault")
    parser.add_argument("--feature-name", required=True, help="Name of the feature to plan")
    parser.add_argument("--description", required=True, help="Description of the feature")
    parser.add_argument("--requirements", nargs="*", default=[], help="Feature requirements")
    parser.add_argument("--acceptance-criteria", nargs="*", default=[], help="Acceptance criteria")

    args = parser.parse_args()

    # If requirements or acceptance criteria are not provided, use defaults
    if not args.requirements:
        args.requirements = ["Core functionality should work as expected",
                            "System should be reliable and performant"]
    if not args.acceptance_criteria:
        args.acceptance_criteria = ["Feature works as described",
                                  "All error conditions are handled gracefully"]

    system = PlanCreationSystem(vault_path=args.vault_path)

    system.run_plan_creation_workflow(
        feature_name=args.feature_name,
        description=args.description,
        requirements=args.requirements,
        acceptance_criteria=args.acceptance_criteria
    )


if __name__ == "__main__":
    main()